// App
export const SOCKET_SETURI = 'SOCKET_SETURI'
export const SOCKET_TRYCONNECTION = 'SOCKET_TRYCONNECTION'
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED'
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED'
export const SOCKET_EMIT = 'SOCKET_EMIT'
export const RESET = 'RESET'
export const RESET_SET = 'RESET_SET'
export const RESET_CLEAR = 'RESET_CLEAR'

// Socket
export const SOCKET_UNBOUND = 'SOCKET_UNBOUND'

// Timer
export const TIMER_START = 'TIMER_START'
export const TIMER_TICK = 'TIMER_TICK'
export const TIMER_END = 'TIMER_END'
export const TIMER_SET_LENGTH = 'TIMER_SET_LENGTH'

// Photo
export const PHOTO_REQUEST = 'PHOTO_REQUEST'
export const PHOTO_REQUEST_RECEIVED = 'PHOTO_REQUEST_RECEIVED'
export const PHOTO_REQUEST_PROCESSING = 'PHOTO_REQUEST_PROCESSING'
export const PHOTO_REQUEST_ERROR = 'PHOTO_REQUEST_ERROR'
export const PHOTO_REQUEST_RESULT = 'PHOTO_REQUEST_RESULT'